// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Consumers;

public partial class SnapshotService
{
    private readonly global::UPnP.Rx.IUpnpService _service;

    /// <summary>Wraps <paramref name="service"/> with the actions <c>Snapshot</c> declares.</summary>
    /// <param name="service">The service to invoke actions on.</param>
    public SnapshotService(global::UPnP.Rx.IUpnpService service) =>
        _service = service ?? throw new ArgumentNullException(nameof(service));

    /// <summary>The service these actions are invoked on.</summary>
    public global::UPnP.Rx.IUpnpService Service => _service;

    /// <summary>Invokes the <c>Awkward</c> action.</summary>
    /// <param name="new_Hyphenated">The <c>New-Hyphenated</c> in-argument.</param>
    /// <param name="class">The <c>Class</c> in-argument.</param>
    /// <param name="_9Leading">The <c>9Leading</c> in-argument.</param>
    /// <param name="ct">Cancels the call.</param>
    /// <exception cref="global::UPnP.Rx.UpnpActionException">The device answered with a SOAP fault.</exception>
    /// <exception cref="global::UPnP.Rx.UpnpException">The exchange failed or the response was unparsable.</exception>
    public async Task AwkwardAsync(string new_Hyphenated, string @class, string _9Leading, CancellationToken ct = default)
    {
        var arguments = new Dictionary<string, string>
        {
            ["New-Hyphenated"] = new_Hyphenated ?? string.Empty,
            ["Class"] = @class ?? string.Empty,
            ["9Leading"] = _9Leading ?? string.Empty,
        };

        await _service.InvokeAsync("Awkward", arguments, ct).ConfigureAwait(false);
    }
}
