// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Consumers;

public partial class SnapshotService
{
    private readonly global::UPnP.Rx.IUpnpService _service;

    /// <summary>Wraps <paramref name="service"/> with the actions <c>Snapshot</c> declares.</summary>
    /// <param name="service">The service to invoke actions on.</param>
    public SnapshotService(global::UPnP.Rx.IUpnpService service) =>
        _service = service ?? throw new ArgumentNullException(nameof(service));

    /// <summary>The service these actions are invoked on.</summary>
    public global::UPnP.Rx.IUpnpService Service => _service;

    /// <summary>The out-arguments of <c>DoEverything</c>.</summary>
    /// <param name="NewResult">The <c>NewResult</c> out-argument (<c>string</c>).</param>
    public sealed record DoEverythingResult(string NewResult);

    /// <summary>Invokes the <c>DoEverything</c> action.</summary>
    /// <param name="newText">The <c>NewText</c> in-argument.</param>
    /// <param name="newCount">The <c>NewCount</c> in-argument; the document allows 1 to 65535.</param>
    /// <param name="newFlag">The <c>NewFlag</c> in-argument.</param>
    /// <param name="newChoice">The <c>NewChoice</c> in-argument.</param>
    /// <param name="ct">Cancels the call.</param>
    /// <exception cref="global::UPnP.Rx.UpnpActionException">The device answered with a SOAP fault.</exception>
    /// <exception cref="global::UPnP.Rx.UpnpException">The exchange failed or the response was unparsable.</exception>
    public async Task<DoEverythingResult> DoEverythingAsync(string newText, ushort newCount, bool newFlag, string newChoice, CancellationToken ct = default)
    {
        if (newCount < 1 || newCount > 65535)
        {
            throw new ArgumentOutOfRangeException(nameof(newCount), newCount,
                "NewCount must be between 1 and 65535, per the service description.");
        }

        if (newChoice != "Alpha" && newChoice != "Beta")
        {
            throw new ArgumentOutOfRangeException(nameof(newChoice), newChoice,
                "NewChoice must be one of 'Alpha' and 'Beta', per the service description.");
        }

        var arguments = new Dictionary<string, string>
        {
            ["NewText"] = newText ?? string.Empty,
            ["NewCount"] = newCount.ToString(global::System.Globalization.CultureInfo.InvariantCulture),
            ["NewFlag"] = newFlag ? "1" : "0",
            ["NewChoice"] = newChoice ?? string.Empty,
        };

        var result = await _service.InvokeAsync("DoEverything", arguments, ct).ConfigureAwait(false);

        return new DoEverythingResult(
            result["NewResult"] ?? string.Empty
        );
    }

    /// <summary>Invokes the <c>NoArguments</c> action.</summary>
    /// <param name="ct">Cancels the call.</param>
    /// <exception cref="global::UPnP.Rx.UpnpActionException">The device answered with a SOAP fault.</exception>
    /// <exception cref="global::UPnP.Rx.UpnpException">The exchange failed or the response was unparsable.</exception>
    public async Task NoArgumentsAsync(CancellationToken ct = default)
    {
        var arguments = new Dictionary<string, string>
        {
        };

        await _service.InvokeAsync("NoArguments", arguments, ct).ConfigureAwait(false);
    }
}
