// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Consumers;

public partial class WanIpConnection
{
    private readonly global::UPnP.Rx.IUpnpService _service;

    /// <summary>Wraps <paramref name="service"/> with the actions <c>WANIPConnection1</c> declares.</summary>
    /// <param name="service">The service to invoke actions on.</param>
    public WanIpConnection(global::UPnP.Rx.IUpnpService service) =>
        _service = service ?? throw new ArgumentNullException(nameof(service));

    /// <summary>The service these actions are invoked on.</summary>
    public global::UPnP.Rx.IUpnpService Service => _service;

    /// <summary>The out-arguments of <c>GetStatusInfo</c>.</summary>
    /// <param name="NewConnectionStatus">The <c>NewConnectionStatus</c> out-argument (<c>string</c>).</param>
    /// <param name="NewLastConnectionError">The <c>NewLastConnectionError</c> out-argument (<c>string</c>).</param>
    /// <param name="NewUptime">The <c>NewUptime</c> out-argument (<c>ui4</c>).</param>
    public sealed record GetStatusInfoResult(string NewConnectionStatus, string NewLastConnectionError, uint NewUptime);

    /// <summary>The out-arguments of <c>GetGenericPortMappingEntry</c>.</summary>
    /// <param name="NewRemoteHost">The <c>NewRemoteHost</c> out-argument (<c>string</c>).</param>
    /// <param name="NewExternalPort">The <c>NewExternalPort</c> out-argument (<c>ui2</c>).</param>
    /// <param name="NewProtocol">The <c>NewProtocol</c> out-argument (<c>string</c>).</param>
    /// <param name="NewInternalPort">The <c>NewInternalPort</c> out-argument (<c>ui2</c>).</param>
    /// <param name="NewInternalClient">The <c>NewInternalClient</c> out-argument (<c>string</c>).</param>
    /// <param name="NewEnabled">The <c>NewEnabled</c> out-argument (<c>boolean</c>).</param>
    /// <param name="NewPortMappingDescription">The <c>NewPortMappingDescription</c> out-argument (<c>string</c>).</param>
    /// <param name="NewLeaseDuration">The <c>NewLeaseDuration</c> out-argument (<c>ui4</c>).</param>
    public sealed record GetGenericPortMappingEntryResult(string NewRemoteHost, ushort NewExternalPort, string NewProtocol, ushort NewInternalPort, string NewInternalClient, bool NewEnabled, string NewPortMappingDescription, uint NewLeaseDuration);

    /// <summary>The out-arguments of <c>GetExternalIPAddress</c>.</summary>
    /// <param name="NewExternalIPAddress">The <c>NewExternalIPAddress</c> out-argument (<c>string</c>).</param>
    public sealed record GetExternalIPAddressResult(string NewExternalIPAddress);

    /// <summary>Invokes the <c>GetStatusInfo</c> action.</summary>
    /// <param name="ct">Cancels the call.</param>
    /// <exception cref="global::UPnP.Rx.UpnpActionException">The device answered with a SOAP fault.</exception>
    /// <exception cref="global::UPnP.Rx.UpnpException">The exchange failed or the response was unparsable.</exception>
    public async Task<GetStatusInfoResult> GetStatusInfoAsync(CancellationToken ct = default)
    {
        var arguments = new Dictionary<string, string>
        {
        };

        var result = await _service.InvokeAsync("GetStatusInfo", arguments, ct).ConfigureAwait(false);

        return new GetStatusInfoResult(
            result["NewConnectionStatus"] ?? string.Empty,
            result["NewLastConnectionError"] ?? string.Empty,
            uint.TryParse(result["NewUptime"], global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var parsedNewUptime) ? parsedNewUptime : default
        );
    }

    /// <summary>Invokes the <c>GetGenericPortMappingEntry</c> action.</summary>
    /// <param name="newPortMappingIndex">The <c>NewPortMappingIndex</c> in-argument.</param>
    /// <param name="ct">Cancels the call.</param>
    /// <exception cref="global::UPnP.Rx.UpnpActionException">The device answered with a SOAP fault.</exception>
    /// <exception cref="global::UPnP.Rx.UpnpException">The exchange failed or the response was unparsable.</exception>
    public async Task<GetGenericPortMappingEntryResult> GetGenericPortMappingEntryAsync(ushort newPortMappingIndex, CancellationToken ct = default)
    {
        var arguments = new Dictionary<string, string>
        {
            ["NewPortMappingIndex"] = newPortMappingIndex.ToString(global::System.Globalization.CultureInfo.InvariantCulture),
        };

        var result = await _service.InvokeAsync("GetGenericPortMappingEntry", arguments, ct).ConfigureAwait(false);

        return new GetGenericPortMappingEntryResult(
            result["NewRemoteHost"] ?? string.Empty,
            ushort.TryParse(result["NewExternalPort"], global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var parsedNewExternalPort) ? parsedNewExternalPort : default,
            result["NewProtocol"] ?? string.Empty,
            ushort.TryParse(result["NewInternalPort"], global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var parsedNewInternalPort) ? parsedNewInternalPort : default,
            result["NewInternalClient"] ?? string.Empty,
            result["NewEnabled"] is "1" or "true" or "yes",
            result["NewPortMappingDescription"] ?? string.Empty,
            uint.TryParse(result["NewLeaseDuration"], global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var parsedNewLeaseDuration) ? parsedNewLeaseDuration : default
        );
    }

    /// <summary>Invokes the <c>AddPortMapping</c> action.</summary>
    /// <param name="newRemoteHost">The <c>NewRemoteHost</c> in-argument.</param>
    /// <param name="newExternalPort">The <c>NewExternalPort</c> in-argument.</param>
    /// <param name="newProtocol">The <c>NewProtocol</c> in-argument.</param>
    /// <param name="newInternalPort">The <c>NewInternalPort</c> in-argument.</param>
    /// <param name="newInternalClient">The <c>NewInternalClient</c> in-argument.</param>
    /// <param name="newEnabled">The <c>NewEnabled</c> in-argument.</param>
    /// <param name="newPortMappingDescription">The <c>NewPortMappingDescription</c> in-argument.</param>
    /// <param name="newLeaseDuration">The <c>NewLeaseDuration</c> in-argument; the document allows 0 to 604800.</param>
    /// <param name="ct">Cancels the call.</param>
    /// <exception cref="global::UPnP.Rx.UpnpActionException">The device answered with a SOAP fault.</exception>
    /// <exception cref="global::UPnP.Rx.UpnpException">The exchange failed or the response was unparsable.</exception>
    public async Task AddPortMappingAsync(string newRemoteHost, ushort newExternalPort, string newProtocol, ushort newInternalPort, string newInternalClient, bool newEnabled, string newPortMappingDescription, uint newLeaseDuration, CancellationToken ct = default)
    {
        if (newProtocol != "TCP" && newProtocol != "UDP")
        {
            throw new ArgumentOutOfRangeException(nameof(newProtocol), newProtocol,
                "NewProtocol must be one of 'TCP' and 'UDP', per the service description.");
        }

        if (newLeaseDuration > 604800)
        {
            throw new ArgumentOutOfRangeException(nameof(newLeaseDuration), newLeaseDuration,
                "NewLeaseDuration must be between 0 and 604800, per the service description.");
        }

        var arguments = new Dictionary<string, string>
        {
            ["NewRemoteHost"] = newRemoteHost ?? string.Empty,
            ["NewExternalPort"] = newExternalPort.ToString(global::System.Globalization.CultureInfo.InvariantCulture),
            ["NewProtocol"] = newProtocol ?? string.Empty,
            ["NewInternalPort"] = newInternalPort.ToString(global::System.Globalization.CultureInfo.InvariantCulture),
            ["NewInternalClient"] = newInternalClient ?? string.Empty,
            ["NewEnabled"] = newEnabled ? "1" : "0",
            ["NewPortMappingDescription"] = newPortMappingDescription ?? string.Empty,
            ["NewLeaseDuration"] = newLeaseDuration.ToString(global::System.Globalization.CultureInfo.InvariantCulture),
        };

        await _service.InvokeAsync("AddPortMapping", arguments, ct).ConfigureAwait(false);
    }

    /// <summary>Invokes the <c>DeletePortMapping</c> action.</summary>
    /// <param name="newRemoteHost">The <c>NewRemoteHost</c> in-argument.</param>
    /// <param name="newExternalPort">The <c>NewExternalPort</c> in-argument.</param>
    /// <param name="newProtocol">The <c>NewProtocol</c> in-argument.</param>
    /// <param name="ct">Cancels the call.</param>
    /// <exception cref="global::UPnP.Rx.UpnpActionException">The device answered with a SOAP fault.</exception>
    /// <exception cref="global::UPnP.Rx.UpnpException">The exchange failed or the response was unparsable.</exception>
    public async Task DeletePortMappingAsync(string newRemoteHost, ushort newExternalPort, string newProtocol, CancellationToken ct = default)
    {
        if (newProtocol != "TCP" && newProtocol != "UDP")
        {
            throw new ArgumentOutOfRangeException(nameof(newProtocol), newProtocol,
                "NewProtocol must be one of 'TCP' and 'UDP', per the service description.");
        }

        var arguments = new Dictionary<string, string>
        {
            ["NewRemoteHost"] = newRemoteHost ?? string.Empty,
            ["NewExternalPort"] = newExternalPort.ToString(global::System.Globalization.CultureInfo.InvariantCulture),
            ["NewProtocol"] = newProtocol ?? string.Empty,
        };

        await _service.InvokeAsync("DeletePortMapping", arguments, ct).ConfigureAwait(false);
    }

    /// <summary>Invokes the <c>GetExternalIPAddress</c> action.</summary>
    /// <param name="ct">Cancels the call.</param>
    /// <exception cref="global::UPnP.Rx.UpnpActionException">The device answered with a SOAP fault.</exception>
    /// <exception cref="global::UPnP.Rx.UpnpException">The exchange failed or the response was unparsable.</exception>
    public async Task<GetExternalIPAddressResult> GetExternalIPAddressAsync(CancellationToken ct = default)
    {
        var arguments = new Dictionary<string, string>
        {
        };

        var result = await _service.InvokeAsync("GetExternalIPAddress", arguments, ct).ConfigureAwait(false);

        return new GetExternalIPAddressResult(
            result["NewExternalIPAddress"] ?? string.Empty
        );
    }
}
